export const ADD_ITEM = "ADD_ITEM";
export const POPULATE_CART = "POPULATE_CART";
export const DELETE_ITEM = "DELETE_ITEM";

export const ADD_ITEM_CART = "ADD_ITEM_CART";
export const POPULATE_TO_CART = "POPULATE_TO_CART";
export const DELETE_ITEM_CART = "DELETE_ITEM_CART";

export const TOGGLE_CART_DRAWER = "TOGGLE_CART_DRAWER";
